services:
  ticket-api:
    build: .
    container_name: ticket-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - API_KEY_USER=${API_KEY_USER}
      - API_KEY_AGENT=${API_KEY_AGENT}
    restart: unless-stopped